spring:
  application:
    name: nyx

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:nyx_products}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:NewStrongPassword!}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  security:
    user:
      name: nyxadmin
      password: nyx1234
      roles: ADMIN

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

pulsar:
  client:
    service-url: ${PULSAR_URL:pulsar://localhost:6650}
  producer:
    product-topic: ${PULSAR_PRODUCT_TOPIC:product-events}

app:
  default-currency: "USD"
  feature-flags:
    publish-product-events: true
